import type {
  AppNotification,
  AssistantResolution,
  HookTransactionEvent,
  ItineraryItem,
  TripSummary,
  WalletSnapshot,
} from '../models/types';

export const MOCK_TRIP: TripSummary = {
  id: 'trip-tokyo-001',
  destination: 'Tokyo',
  destinationCode: 'NRT',
  health: 'on_track',
  healthMessage: 'Everything looks aligned with policy and timing.',
  nextActionTitle: 'Boarding in 45 minutes',
  nextActionSubtitle: 'Gate B12 · ANA 107',
  dailyBudgetUsd: 300,
  approvalStatus: 'approved',
  timelineToday: [
    {
      id: 'tl-1',
      timeLabel: '07:30',
      title: 'Car to airport',
      subtitle: 'Driver confirmed',
    },
    {
      id: 'tl-2',
      timeLabel: '09:15',
      title: 'Depart SFO',
      subtitle: 'ANA 107',
    },
    {
      id: 'tl-3',
      timeLabel: '14:20',
      title: 'Arrive Narita',
      subtitle: 'Immigration & baggage',
    },
    {
      id: 'tl-4',
      timeLabel: '16:00',
      title: 'Hotel check-in',
      subtitle: 'Shinjuku',
    },
    {
      id: 'tl-5',
      timeLabel: '18:30',
      title: 'Client dinner',
      subtitle: 'Walking distance',
    },
  ],
};

export const MOCK_ITINERARY: ItineraryItem[] = [
  {
    id: 'it-1',
    kind: 'flight',
    title: 'SFO → NRT',
    subtitle: 'ANA 107 · Economy',
    startTime: '09:15',
    endTime: '14:20',
    location: 'San Francisco → Tokyo',
    statusBadge: 'safe',
    policyState: 'within_policy',
    spendAmount: 1180,
    spendLimit: 1400,
    vendorApproved: true,
    detailBullets: ['Economy · Lockton preferred carrier', 'Seat 22A', 'Meal: standard'],
  },
  {
    id: 'it-2',
    kind: 'hotel',
    title: 'Hotel New Otani',
    subtitle: '3 nights · Preferred vendor',
    startTime: 'Apr 18',
    endTime: 'Apr 21',
    location: 'Chiyoda, Tokyo',
    statusBadge: 'optimized',
    policyState: 'within_policy',
    spendAmount: 220,
    spendLimit: 300,
    vendorApproved: true,
    detailBullets: ['$220 / $300 nightly limit', 'Breakfast included', 'Corporate rate applied'],
  },
  {
    id: 'it-3',
    kind: 'meeting',
    title: 'Lockton APAC workshop',
    subtitle: 'Client session',
    startTime: '10:00',
    endTime: '12:00',
    location: 'Shinjuku office tower',
    statusBadge: 'safe',
    policyState: 'within_policy',
    spendAmount: 0,
    spendLimit: 0,
    vendorApproved: true,
    detailBullets: ['Internal meeting', 'No spend'],
  },
  {
    id: 'it-4',
    kind: 'flight',
    title: 'NRT → SFO (return)',
    subtitle: 'JL 058 · Business (approval)',
    startTime: 'Apr 21 · 11:40',
    location: 'Tokyo → San Francisco',
    statusBadge: 'risk',
    policyState: 'requires_approval',
    spendAmount: 4200,
    spendLimit: 3200,
    vendorApproved: true,
    detailBullets: ['Business class requires approval', 'Above typical route cap'],
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'n1',
    title: 'Your gate changed',
    body: 'ANA 107 now departs from Gate B12.',
    timeLabel: '12 min ago',
    read: false,
    agent: 'scout',
  },
  {
    id: 'a-scout-1',
    title: 'Geopolitical advisory (Tokyo)',
    body: 'No new travel restrictions for your corridor; monitor Haneda ground ops at peak hours.',
    timeLabel: '18 min ago',
    read: false,
    agent: 'scout',
  },
  {
    id: 'a-treas-1',
    title: 'FX: JPY favorable vs yesterday',
    body: 'Swapping 200 RLUSD → JPY via native AMM now saves ~1.2% vs airport desk rate.',
    timeLabel: '24 min ago',
    read: false,
    agent: 'treasurer',
  },
  {
    id: 'n2',
    title: 'We fixed your booking',
    body: 'Hotel confirmation updated with late checkout.',
    timeLabel: '1 hr ago',
    read: false,
  },
  {
    id: 'n3',
    title: 'Leave now to arrive on time',
    body: 'Traffic is light — suggested departure in 8 minutes.',
    timeLabel: '2 hr ago',
    read: true,
    agent: 'scout',
  },
  {
    id: 'a-treas-2',
    title: 'Trip escrow topped up',
    body: 'Corporate treasury funded trip escrow (+$300 RLUSD). Hook policy active for hotel + air.',
    timeLabel: '3 hr ago',
    read: true,
    agent: 'treasurer',
  },
];

export const MOCK_WALLET: WalletSnapshot = {
  did: 'did:xrpl:1:mainnet:rN8qJfJ7g4hK2vP9xL3mQ5wZ1cY6bT0sD4e',
  rlusdBalance: '4,280.52',
  xrpBalance: '1,204.33',
  tripEscrowUsd: '300.00',
  lendingVaultAvailableUsd: '50,000.00',
};

export const MOCK_HOOK_EVENTS: HookTransactionEvent[] = [
  {
    id: 'hx-1',
    timeLabel: 'Just now',
    merchant: 'ANA · In-flight purchase',
    category: 'airline',
    amountUsd: 42,
    decision: 'passed',
    companionAuthorized: true,
    reference: 'HOOK-ANA-88421',
    hookChecks: [
      { id: 'c1', label: 'Merchant on approved airline list', ok: true },
      { id: 'c2', label: 'Companion signature valid for trip NRT-001', ok: true },
      { id: 'c3', label: 'Trip escrow ≥ spend', ok: true },
    ],
  },
  {
    id: 'hx-2',
    timeLabel: '6 min ago',
    merchant: 'Hotel New Otani · Deposit',
    category: 'hotel',
    amountUsd: 220,
    decision: 'passed',
    companionAuthorized: true,
    reference: 'HOOK-HTL-22104',
    hookChecks: [
      { id: 'c1', label: 'Merchant is registered hotel vendor', ok: true },
      { id: 'c2', label: 'Companion authorized for lodging', ok: true },
      { id: 'c3', label: 'RLUSD in trip escrow', ok: true },
    ],
  },
  {
    id: 'hx-3',
    timeLabel: 'Yesterday',
    merchant: 'Unknown vendor · Ground transport',
    category: 'ground',
    amountUsd: 180,
    decision: 'blocked',
    companionAuthorized: true,
    reference: 'HOOK-BLK-0092',
    hookChecks: [
      { id: 'c1', label: 'Merchant on approved vendor list', ok: false },
      { id: 'c2', label: 'Companion signature valid', ok: true },
      { id: 'c3', label: 'Escrow sufficient', ok: true },
    ],
  },
  {
    id: 'hx-4',
    timeLabel: 'Pending',
    merchant: 'Business class upgrade · JL 058',
    category: 'airline',
    amountUsd: 4200,
    decision: 'pending',
    companionAuthorized: false,
    hookChecks: [
      { id: 'c1', label: 'Merchant on approved airline list', ok: true },
      { id: 'c2', label: 'Companion proof of intent (policy)', ok: false },
      { id: 'c3', label: 'Within route cap', ok: false },
    ],
  },
];

export function mockAssistantResolution(): AssistantResolution {
  return {
    message: "I've found 2 better options that keep you within policy and save time.",
    suggestions: [
      {
        id: 's1',
        title: 'Earlier ANA flight',
        summary: 'Arrives 55 minutes sooner, same fare class, preferred vendor.',
        priceUsd: 1165,
        savingsUsd: 40,
        etaMinutes: -55,
      },
      {
        id: 's2',
        title: 'Hotel swap · Shinjuku',
        summary: 'Closer to tomorrow’s meetings, within nightly limit, breakfast included.',
        priceUsd: 265,
        savingsUsd: 0,
      },
    ],
  };
}
